KcOidcBrokerTest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,96 +54,96 @@ jobs:
 
 # Tests: Regular distribution
 
-  unit-tests:
-    name: Unit Tests
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: ${{ env.DEFAULT_JDK_VERSION }}
-          cache: 'maven'
-      - name: Update maven settings
-        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
-      - name: Cleanup org.keycloak artifacts
-        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true
-      - name: Download built keycloak
-        id: download-keycloak
-        uses: actions/download-artifact@v3
-        with:
-          path: ~/.m2/repository/org/keycloak/
-          name: keycloak-artifacts.zip
-      - name: Run unit tests
-        run: |
-          if ! ./mvnw install -nsu -B -DskipTestsuite -DskipQuarkus -DskipExamples -f pom.xml; then
-            find . -path '*/target/surefire-reports/*.xml' | zip -q reports-unit-tests.zip -@
-            exit 1
-          fi
-
-      - name: Analyze Test and/or Coverage Results
-        uses: runforesight/foresight-test-kit-action@v1.2.1
-        if: always() && github.repository == 'keycloak/keycloak'
-        with:
-          api_key: ${{ secrets.FORESIGHT_API_KEY }}
-          test_format: JUNIT
-          test_framework: JUNIT
-          test_path: '**/target/surefire-reports/*.xml'
-
-      - name: Unit test reports
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: reports-unit-tests
-          retention-days: 14
-          path: reports-unit-tests.zip
-          if-no-files-found: ignore
-
-  crypto-tests:
-    name: Crypto Tests
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: ${{ env.DEFAULT_JDK_VERSION }}
-          cache: 'maven'
-      - name: Update maven settings
-        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
-      - name: Cleanup org.keycloak artifacts
-        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true
-      - name: Download built keycloak
-        id: download-keycloak
-        uses: actions/download-artifact@v3
-        with:
-          path: ~/.m2/repository/org/keycloak/
-          name: keycloak-artifacts.zip
-      - name: Run crypto tests (BCFIPS non-approved mode)
-        run: |
-          if ! ./mvnw install -nsu -B -f crypto/pom.xml -Dcom.redhat.fips=true; then
-            find . -path 'crypto/target/surefire-reports/*.xml' | zip -q reports-crypto-tests.zip -@
-            exit 1
-          fi
-
-      - name: Run crypto tests (BCFIPS approved mode)
-        run: |
-          if ! ./mvnw install -nsu -B -f crypto/pom.xml -Dcom.redhat.fips=true -Dorg.bouncycastle.fips.approved_only=true; then
-            find . -path 'crypto/target/surefire-reports/*.xml' | zip -q reports-crypto-tests.zip -@
-            exit 1
-          fi          
-
-      - name: Crypto test reports
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: reports-crypto-tests
-          retention-days: 14
-          path: reports-crypto-tests.zip
-          if-no-files-found: ignore
-
+#  unit-tests:
+#    name: Unit Tests
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin'
+#          java-version: ${{ env.DEFAULT_JDK_VERSION }}
+#          cache: 'maven'
+#      - name: Update maven settings
+#        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
+#      - name: Cleanup org.keycloak artifacts
+#        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true
+#      - name: Download built keycloak
+#        id: download-keycloak
+#        uses: actions/download-artifact@v3
+#        with:
+#          path: ~/.m2/repository/org/keycloak/
+#          name: keycloak-artifacts.zip
+#      - name: Run unit tests
+#        run: |
+#          if ! ./mvnw install -nsu -B -DskipTestsuite -DskipQuarkus -DskipExamples -f pom.xml; then
+#            find . -path '*/target/surefire-reports/*.xml' | zip -q reports-unit-tests.zip -@
+#            exit 1
+#          fi
+#
+#      - name: Analyze Test and/or Coverage Results
+#        uses: runforesight/foresight-test-kit-action@v1.2.1
+#        if: always() && github.repository == 'keycloak/keycloak'
+#        with:
+#          api_key: ${{ secrets.FORESIGHT_API_KEY }}
+#          test_format: JUNIT
+#          test_framework: JUNIT
+#          test_path: '**/target/surefire-reports/*.xml'
+#
+#      - name: Unit test reports
+#        uses: actions/upload-artifact@v3
+#        if: failure()
+#        with:
+#          name: reports-unit-tests
+#          retention-days: 14
+#          path: reports-unit-tests.zip
+#          if-no-files-found: ignore
+#
+#  crypto-tests:
+#    name: Crypto Tests
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin'
+#          java-version: ${{ env.DEFAULT_JDK_VERSION }}
+#          cache: 'maven'
+#      - name: Update maven settings
+#        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
+#      - name: Cleanup org.keycloak artifacts
+#        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true
+#      - name: Download built keycloak
+#        id: download-keycloak
+#        uses: actions/download-artifact@v3
+#        with:
+#          path: ~/.m2/repository/org/keycloak/
+#          name: keycloak-artifacts.zip
+#      - name: Run crypto tests (BCFIPS non-approved mode)
+#        run: |
+#          if ! ./mvnw install -nsu -B -f crypto/pom.xml -Dcom.redhat.fips=true; then
+#            find . -path 'crypto/target/surefire-reports/*.xml' | zip -q reports-crypto-tests.zip -@
+#            exit 1
+#          fi
+#
+#      - name: Run crypto tests (BCFIPS approved mode)
+#        run: |
+#          if ! ./mvnw install -nsu -B -f crypto/pom.xml -Dcom.redhat.fips=true -Dorg.bouncycastle.fips.approved_only=true; then
+#            find . -path 'crypto/target/surefire-reports/*.xml' | zip -q reports-crypto-tests.zip -@
+#            exit 1
+#          fi
+#
+#      - name: Crypto test reports
+#        uses: actions/upload-artifact@v3
+#        if: failure()
+#        with:
+#          name: reports-crypto-tests
+#          retention-days: 14
+#          path: reports-crypto-tests.zip
+#          if-no-files-found: ignore
+#
   model-tests:
     name: Model Tests
     runs-on: ubuntu-latest
@@ -246,11 +246,11 @@ jobs:
           PARAMS["quarkus"]="-Pauth-server-quarkus"
           PARAMS["quarkus-map"]="-Pauth-server-quarkus -Pmap-storage -Dpageload.timeout=90000"
           PARAMS["quarkus-map-hot-rod"]="-Pauth-server-quarkus -Pmap-storage,map-storage-hot-rod -Dpageload.timeout=90000"
-          TESTGROUP["group1"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.(a[abc]|ad[a-l]|[^a-q]).*]"   # Tests alphabetically before admin tests and those after "r"
-          TESTGROUP["group2"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.(ad[^a-l]|a[^a-d]|b).*]"      # Admin tests and those starting with "b"
-          TESTGROUP["group3"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.([c-q]).*]"                   # All the rest
+#          TESTGROUP["group1"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.(a[abc]|ad[a-l]|[^a-q]).*]"   # Tests alphabetically before admin tests and those after "r"
+#          TESTGROUP["group2"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.(ad[^a-l]|a[^a-d]|b).*]"      # Admin tests and those starting with "b"
+#          TESTGROUP["group3"]="-Dtest=!**.crossdc.**,!**.cluster.**,%regex[org.keycloak.testsuite.([c-q]).*]"                   # All the rest
 
-          ./mvnw clean install -nsu -B ${PARAMS["${{ matrix.server }}"]} ${TESTGROUP["${{ matrix.tests }}"]} -f testsuite/integration-arquillian/tests/base/pom.xml | misc/log/trimmer.sh
+          ./mvnw clean install -nsu -B ${PARAMS["${{ matrix.server }}"]} -Dtest=KcOidcBrokerTest -f testsuite/integration-arquillian/tests/base/pom.xml
 
           TEST_RESULT=${PIPESTATUS[0]}
           find . -path '*/target/surefire-reports/*.xml' | zip -q reports-${{ matrix.server }}-base-tests-${{ matrix.tests }}.zip -@
